# Generated by Django 5.1.1 on 2024-09-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_admindetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=222, upload_to='img'),
            preserve_default=False,
        ),
    ]
